# tiny makefile to automatize repeatitive tasks

all: topng

topng:
	./thenounproject2png.sh noun_project_179.svg options.png
	./thenounproject2png.sh noun_project_473.svg camera.png
	./thenounproject2png.sh noun_project_328.svg talk.png
	./thenounproject2png.sh noun_project_22.svg help.png
